services:
  scheduler-mongodb:
    image: mongo
    restart: always
    container_name: scheduler-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: scheduler-items
    ports:
      - 27023:27017
    volumes:
      - ./db:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  scheduler-mongodb-express:
    image: mongo-express
    restart: always
    container_name: scheduler-mongo-express
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@scheduler-mongodb:27017/
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
