### СОЗДАНИЕ ЭЛЕМЕНТА
POST http://localhost:3001/items HTTP/1.1
Content-Type: application/json

{
  "title": "Новый список",
  "description": "TODO список важных дел",
  "listsIds": [],
  "consistsOfItemsIds": [],
  "deadline": null,
  "type": "TODO_LIST"
}

###=============================================СПИСКИ=============================================

### СОЗДАНИЕ СПИСКА
POST http://localhost:3001/lists HTTP/1.1
Content-Type: application/json

{
  "title": "List example"
}

### ПОЛУЧЕНИЕ СПИСКА СПИСКОВ
GET http://localhost:3001/lists HTTP/1.1

### УДАЛЕНИЕ СПИСКА
DELETE http://localhost:3001/lists/64a2d4aa9768973391f8ea7e HTTP/1.1

### ОБНОВЛЕНИЕ СПИСКА
PATCH http://localhost:3001/lists/64a26d3e43a4702cfa1351c7
Content-Type: application/json

{
  "title": "qwerty"
}
